#!/usr/bin/env python3

import argparse
import yaml

import srv6_ping
from srv6_ping.ping import ping_and_show, new_srh_tlv


def get_args(description=None):
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument('-c', '--count', type=int, default=5, help="ping count")
    parser.add_argument('-d', '--dst', help="destination ipv6 address")
    parser.add_argument('--src', help="source ipv6 address")
    parser.add_argument('-s', '--segs', default="", help="segment_list. (e.g. fd0a::,fd0b::,fd0c::)")
    parser.add_argument('-t', '--timeout', default=3, help="timeout")
    parser.add_argument('-j', '--json_format', action='store_true')
    parser.add_argument('-f', '--conf_file', help="config file")

    parser.add_argument('--oam', type=bool, default=True, help="srh oam flag")
    parser.add_argument('--hlim', type=int, default=64, help="IPv6 hop limit")
    parser.add_argument('--including_srh', type=bool, default=True, help="always including_srh")
    parser.add_argument('--iface', type=str, default=None, help="out interface")

    parser.add_argument('-v', '--verbose', action='store_true')

    args = parser.parse_args()
    return args


def run_from_yaml(yaml_file):
    with open(yaml_file) as f:
        conf = yaml.safe_load(f)
    ping_conf = conf.get("ping", [])
    for dest in ping_conf:
        srh_tlvs = []
        for tlv in dest.get("srh_tlvs", []):
            srh_tlvs.append(new_srh_tlv(type=tlv["type"], value=tlv["value"]))
        pkt_params = {
            "dst": dest["destination"],
            "segs": dest.get("segs"),
            "hlim": dest.get("hlim", 64),
            "srh_tlvs": srh_tlvs
        }
        ping_and_show(timeout=dest.get("timeout", 3), max_count=dest.get("count", 1),
                      json_format=dest.get("json_format", False), pkt_params=pkt_params)


if __name__ == '__main__':
    args = get_args()
    srv6_ping.verbose = args.verbose
    if args.conf_file:
        run_from_yaml(args.conf_file)
    else:
        pkt_params = {
            "src": args.src,
            "dst": args.dst,
            "segs": args.segs.split(","),
            "hlim": args.hlim,
            "including_srh": args.including_srh,
            "oam": args.oam,
        }
        ping_and_show(timeout=args.timeout, max_count=args.count, iface=args.iface, json_format=args.json_format, pkt_params=pkt_params)
