#!/usr/bin/env python3

import argparse
from srv6_ping.ping import ping_and_show


def get_args(description=None):
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument('-c', '--count', type=int, help="ping count")
    parser.add_argument('-d', '--destination', help="destination", required=True)
    parser.add_argument('-s', '--segs', default="", help="segment_list. (e.g. fd0a::,fd0b::,fd0c::)")
    parser.add_argument('-t', '--timeout', default=3, help="timeout")
    parser.add_argument('-j', '--json_format', action='store_true')

    args = parser.parse_args()
    return args


if __name__ == '__main__':
    args = get_args()
    ping_and_show(args.destination, args.segs.split(","), timeout=args.timeout, max_count=args.count, json_format=args.json_format)
