name: Run ping test
on: [push]

jobs:
  pytest:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: setup module
        run: |
          git submodule init
          git submodule sync
          git submodule update
      - name: install
        run: |
          sudo ./install.sh
      - name: run unit test
        run: |
          sudo ./test_srv6_ping.sh